# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14lxOXeZGb6E4iOjtf2ifwKAY0AOWPPaS
"""

import streamlit as st
import torch
import torch.nn as nn
from torchvision import models, transforms
from PIL import Image
import os

# Define exact training classes in alphabetical order
CLASSES = ['buildings', 'forest', 'glacier', 'mountain', 'sea', 'street']
IMAGE_SIZE = 150

# Page configuration
st.set_page_config(
    page_title="Satellite Scene Classifier",
    page_icon="🛰️",
    layout="centered"
)

# Custom professional CSS styling
st.markdown('''
    <style>
    .main-title { font-size: 2.4rem; font-weight: 700; color: #1E3A8A; text-align: center; margin-bottom: 5px; }
    .sub-title { font-size: 1.1rem; color: #4B5563; text-align: center; margin-bottom: 25px; }
    .prediction-box { padding: 15px; border-radius: 8px; background-color: #EFF6FF; border: 1px solid #BFDBFE; text-align: center; margin-top: 15px; }
    .prediction-label { font-size: 1.5rem; font-weight: 700; color: #1D4ED8; }
    </style>
''', unsafe_allow_html=True)

st.markdown('<div class="main-title">🛰️ Satellite Scene Automated Classifier</div>', unsafe_allow_html=True)
st.markdown('<div class="sub-title">Domain-Specific Deep Learning Deployment Portal</div>', unsafe_allow_html=True)

@st.cache_resource
def load_trained_classifier():
    """Reconstructs the ResNet18 architecture and loads fine-tuned weights."""
    model = models.resnet18()

    # Freeze foundational feature extraction layers
    for param in model.parameters():
        param.requires_grad = False

    # Reconstruct the classification head to map out the 6 target categories
    num_features = model.fc.in_features
    model.fc = nn.Linear(num_features, len(CLASSES))

    # Check for weights file in the local directory
    weights_filename = 'refined_satellite_model.pth'
    if os.path.exists(weights_filename):
        model.load_state_dict(torch.load(weights_filename, map_location=torch.device('cpu')))
        model.eval()
        return model, True
    return model, False

model, weights_loaded = load_trained_classifier()

# Display loading state status banner
if not weights_loaded:
    st.error("❌ Critical Error: 'refined_satellite_model.pth' not detected in the workspace root directory.")
else:
    st.success("✅ Authentic Fine-Tuned ResNet18 Weights Successfully Ingested!")

# Preprocessing transformations matching the validation pipeline
inference_transforms = transforms.Compose([
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

uploaded_file = st.file_uploader("Upload an aerial or natural scene snapshot...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert('RGB')
    col1, col2 = st.columns([1, 1])

    with col1:
        st.write("#### 📸 Input Target Frame")
        st.image(image, use_container_width=True)

    with col2:
        st.write("#### 🔬 Model Prediction")
        tensor_img = inference_transforms(image).unsqueeze(0)

        with torch.no_grad():
            logits_output = model(tensor_img)
            probabilities = torch.nn.functional.softmax(logits_output[0], dim=0)
            confidence_score, highest_class_idx = torch.max(probabilities, 0)

        predicted_class_name = CLASSES[highest_class_idx.item()].upper()
        confidence_percentage = confidence_score.item() * 100

        st.markdown(f'''
            <div class="prediction-box">
                <span style="font-size: 0.9rem; color: #4B5563; font-weight: 600; text-transform: uppercase;">Classification Output</span>
                <div class="prediction-label">{predicted_class_name}</div>
                <span style="font-size: 1.1rem; font-weight: 600; color: #1E3A8A;">Confidence: {confidence_percentage:.2f}%</span>
            </div>
        ''', unsafe_allow_html=True)

    st.write("---")
    st.write("📊 **Granular Softmax Probability Distribution Breakdown:**")
    for index, class_name in enumerate(CLASSES):
        prob_val = float(probabilities[index].item())
        if index == highest_class_idx.item():
            label = f"🔹 **{class_name.capitalize()} (Target Match)**"
        else:
            label = f"{class_name.capitalize()}"
        st.write(f"{label}: `{prob_val * 100:.1f}%`")
        st.progress(prob_val)